### ISSUE TITLE
javax.swing.JLabel cannot be cast to org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel

### ISSUE THREAD

**Issue by lure0xaos** [andrepdo/findbugs-idea#125] opened 2016-05-27 18:12 UTC
The error was copied to the clipboard. Press Ctrl+V

**Comment by retomerz** [comment] 2016-05-28 14:53
Duplicate of issue #124

**Closed by retomerz** 2016-05-28 14:53 UTC
Labels: duplicate
