### ISSUE TITLE
javax.swing.JLabel cannot be cast to org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel

### ISSUE THREAD

**Issue by BorzdeG** [andrepdo/findbugs-idea#127] opened 2016-05-28 08:12 UTC
javax.swing.JLabel cannot be cast to org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel
java.lang.ClassCastException: javax.swing.JLabel cannot be cast to org.twodividedbyzero.idea.findbugs.gui.toolwindow.view.ToolWindowPanel
	at org.twodividedbyzero.idea.findbugs.actions.ShowQuickSearch.actionPerformedImpl(ShowQuickSearch.java:54)
	at org.twodividedbyzero.idea.findbugs.actions.AbstractAction.actionPerformed(AbstractAction.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:635)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by retomerz** [comment] 2016-05-28 15:18
Duplicate of issue #124

**Closed by retomerz** 2016-05-28 15:18 UTC
Labels: duplicate
